### ISSUE TITLE
Why does ImmortalList not implement Iterable?

### ISSUE THREAD

**Issue by Jonas-Sander** [strangeAeon/immortal#1]
![image](https://user-images.githubusercontent.com/29028262/90661195-2f291b80-e247-11ea-82ee-397389d2dba7.png)

**Comment by strangeAeon** [comment]
Sorry for the late answer :sweat_smile: 

I have thought a lot about this in the beginning and I have been annoyed by it often enough myself by now, so I introduced this in the just released version `3.0.0-nullsafety` :tada: (One of the dependencies is still a pre-release)

Initially I deliberately chose not to as I prefer the more functional approach to return optionals instead of throwing exceptions when an element was not found (e.g. for retrieving an element at a specific position, `firstWhere` etc.). As I already did not implement the `List` interface I felt no pressure to squeeze the immortal collections into the `Iterable` interface either.

Over time I could not ignore the conveniances provided by this interface, espc. in the context of Flutter widgets, so I finally gave in to the `Iterable` interface and provide alternative versions returning optionals for functions like `elementAt`/`first`/`last` etc. under different names additionally.

However, I only did so for `ImmortalList` and not for `ImmortalSet`, as I would rather not encourage relying on the order of elements in a set (even though the implementation might actually provide a stable order).
